#' A function to plot trace outcome from a Markov or Microsimulation 
#'
#' This function generates a graph from the Markov or Micro Trace 
#' The graph shows distribution of the cohort (of inidvidual subjects) over the different health states per cycle.
#' @param trace Trace generated by `CalculateMarkovTrace` function or "CalculateMicroTrace" 
#' @param xlab x-axis label
#' @param title Title of the plot, e.g. "Markov Trace" or "Microsimulation Trace" 
#' @param txtsize Text size for plot, default = 12
#' @keywords Markov; plot; graph
#' @return plot_trace ggplot of the Markov trace  
#' PlotTrace()


PlotTrace <- function(trace, title, xlab, txtsize = 12){

  trace <- data.frame(time = seq(0, (nrow(trace)-1)), trace)
  trace <- melt(trace, id.vars = "time")
  plot_trace <- ggplot(trace, aes(x = time, y = value, colour = variable)) +
    geom_line() +
    scale_colour_hue("States ", l = 50) +
    ggtitle(title) +
    xlab(xlab) +
    ylab("Proportion") +
    theme_bw() +
    theme(title = element_text(face = "bold", size = 14),
          axis.title.x = element_text(face = "bold", size = txtsize),
          axis.title.y = element_text(face = "bold", size = txtsize),
          axis.text.y  = element_text(size = txtsize),
          axis.text.x  = element_text(size = txtsize))
  print(plot_trace)
  
  return(plot_trace)
}
